CREATE TABLE `articles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`slug` varchar(255) NOT NULL,
	`title` varchar(512) NOT NULL,
	`metaDescription` varchar(320),
	`ogTitle` varchar(512),
	`ogDescription` varchar(320),
	`category` varchar(128),
	`tags` json DEFAULT ('[]'),
	`imageUrl` text,
	`imageAlt` varchar(320),
	`heroImageUrl` text,
	`body` text NOT NULL,
	`wordCount` int DEFAULT 0,
	`readingTime` int DEFAULT 0,
	`author` varchar(64) NOT NULL DEFAULT 'Kalesh',
	`ctaPrimary` text,
	`asinsUsed` json DEFAULT ('[]'),
	`openerType` enum('gut-punch','question','story','counterintuitive'),
	`conclusionType` enum('call-to-action','reflection','question','challenge','benediction'),
	`hasKaleshBacklink` boolean DEFAULT false,
	`faqCount` int DEFAULT 0,
	`status` enum('draft','published','archived') NOT NULL DEFAULT 'published',
	`lastRefreshed30d` timestamp,
	`lastRefreshed90d` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`publishedAt` timestamp DEFAULT (now()),
	CONSTRAINT `articles_id` PRIMARY KEY(`id`),
	CONSTRAINT `articles_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
CREATE TABLE `products` (
	`id` int AUTO_INCREMENT NOT NULL,
	`asin` varchar(10) NOT NULL,
	`name` varchar(512) NOT NULL,
	`category` varchar(128) NOT NULL,
	`tags` json DEFAULT ('[]'),
	`verifiedAt` timestamp,
	`lastChecked` timestamp,
	`status` enum('valid','invalid','pending') NOT NULL DEFAULT 'pending',
	`lastSpotlightedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `products_id` PRIMARY KEY(`id`),
	CONSTRAINT `products_asin_unique` UNIQUE(`asin`)
);
