/**
 * bulk-seed.mjs
 * Seeds 500 unique conscious aging article topics into the articles table
 * with status='queued' and queuedAt set. The cron Phase 2 publisher
 * will promote them to 'published' one per day with a Bunny CDN hero image.
 *
 * Usage: node scripts/bulk-seed.mjs [--dry-run] [--limit=N]
 * Env:   DATABASE_URL, OPENAI_API_KEY (DeepSeek V4-Pro via OpenAI client)
 */

import mysql from 'mysql2/promise';
import dotenv from 'dotenv';
dotenv.config();

const DRY_RUN = process.argv.includes('--dry-run');
const limitArg = process.argv.find(a => a.startsWith('--limit='));
const LIMIT = limitArg ? parseInt(limitArg.split('=')[1], 10) : 500;

// 500 unique conscious aging topics across 10 categories
const TOPICS = [
  // ── Physical Wellness (50) ──────────────────────────────────────────────
  { title: "Why Your Doctor Doesn't Know About Fascia (And Why You Should)", category: "Physical Wellness" },
  { title: "The One Stretch That Changed My Morning Routine at 60", category: "Physical Wellness" },
  { title: "Cold Showers After 60: What Nobody Tells You", category: "Physical Wellness" },
  { title: "How I Got Off Three Medications With One Habit Change", category: "Physical Wellness" },
  { title: "The Truth About Protein After 65 (You're Probably Not Eating Enough)", category: "Physical Wellness" },
  { title: "Walking Backwards: The Weird Exercise That Fixed My Knees", category: "Physical Wellness" },
  { title: "Why Older Adults Sleep Less (And What To Do About It)", category: "Physical Wellness" },
  { title: "The Gut-Brain Connection Nobody Talks About After 60", category: "Physical Wellness" },
  { title: "Zone 2 Cardio: The Boring Workout That Might Save Your Life", category: "Physical Wellness" },
  { title: "What Happens to Your Muscles If You Stop Moving for Two Weeks", category: "Physical Wellness" },
  { title: "The Case Against Sitting: How I Built a Movement Practice at 67", category: "Physical Wellness" },
  { title: "Rucking: Why Carrying Weight on Walks Is the Best Thing I've Done", category: "Physical Wellness" },
  { title: "Why Balance Training Matters More Than Cardio After 60", category: "Physical Wellness" },
  { title: "The Inflammation Connection: What I Eat Now Versus What I Ate at 40", category: "Physical Wellness" },
  { title: "Grip Strength Is a Longevity Marker. Here's How to Improve Yours", category: "Physical Wellness" },
  { title: "How I Fixed My Posture After 30 Years of Desk Work", category: "Physical Wellness" },
  { title: "The Surprising Benefits of Napping After 60", category: "Physical Wellness" },
  { title: "Why I Started Swimming at 63 and What It Did to My Brain", category: "Physical Wellness" },
  { title: "Magnesium: The Mineral Most Older Adults Are Missing", category: "Physical Wellness" },
  { title: "How to Build Strength Without a Gym After 65", category: "Physical Wellness" },
  { title: "The Difference Between Fatigue and Exhaustion (And Why It Matters)", category: "Physical Wellness" },
  { title: "Why Your Breathing Pattern Is Aging You Faster", category: "Physical Wellness" },
  { title: "The Foot-Health Connection Most Doctors Ignore", category: "Physical Wellness" },
  { title: "How I Reversed My Pre-Diabetes With Food Alone", category: "Physical Wellness" },
  { title: "What Yoga Actually Does to Your Nervous System After 60", category: "Physical Wellness" },
  { title: "The Hydration Mistake Most Older Adults Make Every Day", category: "Physical Wellness" },
  { title: "Why I Gave Up Alcohol at 62 (And What Happened Next)", category: "Physical Wellness" },
  { title: "The Case for Strength Training Over Cardio After Menopause", category: "Physical Wellness" },
  { title: "How to Read a Blood Panel When You're Over 60", category: "Physical Wellness" },
  { title: "The Sleep Position That's Ruining Your Neck", category: "Physical Wellness" },
  { title: "Why Older Adults Need More Sunlight, Not Less", category: "Physical Wellness" },
  { title: "The Lymphatic System: Why Moving It Matters After 60", category: "Physical Wellness" },
  { title: "How I Healed My Chronic Back Pain Without Surgery", category: "Physical Wellness" },
  { title: "The Connection Between Oral Health and Heart Disease After 60", category: "Physical Wellness" },
  { title: "Why I Stopped Taking Statins (And What My Doctor Said)", category: "Physical Wellness" },
  { title: "The Hormone Changes Nobody Prepares Men For After 60", category: "Physical Wellness" },
  { title: "How to Exercise When Everything Hurts", category: "Physical Wellness" },
  { title: "The Anti-Inflammatory Diet I Actually Stick To", category: "Physical Wellness" },
  { title: "Why Your Body Needs More Recovery Time as You Age", category: "Physical Wellness" },
  { title: "The Difference Between Healthy Aging and Slow Decline", category: "Physical Wellness" },
  { title: "How I Started Running Again at 64 After a Knee Replacement", category: "Physical Wellness" },
  { title: "Why Fiber Is the Most Underrated Nutrient After 60", category: "Physical Wellness" },
  { title: "The Science of Sarcopenia (And How to Fight It)", category: "Physical Wellness" },
  { title: "What a Physical Therapist Told Me That My Doctor Never Did", category: "Physical Wellness" },
  { title: "How I Use a Sauna to Manage Stress and Inflammation", category: "Physical Wellness" },
  { title: "The Breathing Exercise That Lowers My Blood Pressure in 10 Minutes", category: "Physical Wellness" },
  { title: "Why I Started Eating More Fat at 65 (And What Changed)", category: "Physical Wellness" },
  { title: "The Morning Routine That Keeps Me Off Prescription Sleep Aids", category: "Physical Wellness" },
  { title: "How to Tell the Difference Between Normal Aging and Something Wrong", category: "Physical Wellness" },
  { title: "The One Supplement I Actually Trust After Trying Dozens", category: "Physical Wellness" },

  // ── Mental Clarity (50) ─────────────────────────────────────────────────
  { title: "What I Learned From Getting a Cognitive Baseline Test at 62", category: "Mental Clarity" },
  { title: "The Brain Fog That Disappeared When I Changed One Thing", category: "Mental Clarity" },
  { title: "Why Learning Something New Is the Best Brain Exercise", category: "Mental Clarity" },
  { title: "How I Use Journaling to Keep My Mind Sharp", category: "Mental Clarity" },
  { title: "The Difference Between Normal Forgetfulness and Early Dementia", category: "Mental Clarity" },
  { title: "Why I Started Playing Chess at 66 (And What It Did to My Focus)", category: "Mental Clarity" },
  { title: "The Connection Between Gut Health and Memory After 60", category: "Mental Clarity" },
  { title: "How Sleep Deprivation Accelerates Cognitive Decline", category: "Mental Clarity" },
  { title: "Why Boredom Is Actually Good for Your Brain", category: "Mental Clarity" },
  { title: "The Omega-3 Question: What the Research Actually Says", category: "Mental Clarity" },
  { title: "How I Trained My Brain to Focus in a World of Distractions", category: "Mental Clarity" },
  { title: "The Surprising Link Between Hearing Loss and Dementia Risk", category: "Mental Clarity" },
  { title: "Why Older Adults Are Often Better Decision-Makers Than Young People", category: "Mental Clarity" },
  { title: "How I Use Music to Access Memory and Emotion", category: "Mental Clarity" },
  { title: "The Case for Doing Hard Things After 60", category: "Mental Clarity" },
  { title: "What Meditation Does to the Aging Brain (The Research Is Striking)", category: "Mental Clarity" },
  { title: "How I Stopped Multitasking and Got My Focus Back", category: "Mental Clarity" },
  { title: "The Social Isolation-Cognitive Decline Connection Nobody Talks About", category: "Mental Clarity" },
  { title: "Why I Read Physical Books Instead of Screens After 60", category: "Mental Clarity" },
  { title: "The Memory Palace Technique I Use Every Day", category: "Mental Clarity" },
  { title: "How to Keep Your Brain Plastic After 65", category: "Mental Clarity" },
  { title: "Why Curiosity Is the Most Protective Cognitive Trait", category: "Mental Clarity" },
  { title: "The Alcohol-Brain Connection: What I Wish I'd Known at 50", category: "Mental Clarity" },
  { title: "How I Use Crossword Puzzles (And Why They're Not Enough)", category: "Mental Clarity" },
  { title: "The Role of Purpose in Cognitive Longevity", category: "Mental Clarity" },
  { title: "Why I Started Learning Spanish at 68", category: "Mental Clarity" },
  { title: "The Stress-Memory Connection: How Chronic Stress Shrinks Your Brain", category: "Mental Clarity" },
  { title: "How I Use Walking to Solve Problems I Can't Crack at My Desk", category: "Mental Clarity" },
  { title: "The Difference Between Wisdom and Intelligence as We Age", category: "Mental Clarity" },
  { title: "Why I Stopped Watching the News Before Bed", category: "Mental Clarity" },
  { title: "How to Build a Brain-Healthy Home Environment", category: "Mental Clarity" },
  { title: "The Case for Handwriting in a Digital World", category: "Mental Clarity" },
  { title: "Why Older Adults Often Have Better Emotional Regulation", category: "Mental Clarity" },
  { title: "The Vitamin D-Brain Health Connection I Ignored for Too Long", category: "Mental Clarity" },
  { title: "How I Use Spaced Repetition to Remember What I Read", category: "Mental Clarity" },
  { title: "The Connection Between Physical Exercise and Brain Volume", category: "Mental Clarity" },
  { title: "Why I Started a Daily Gratitude Practice (And What Changed)", category: "Mental Clarity" },
  { title: "How to Have a Harder Conversation Than You Think You Can", category: "Mental Clarity" },
  { title: "The Cognitive Benefits of Teaching What You Know", category: "Mental Clarity" },
  { title: "Why I Gave Up Multivitamins and Started Eating Real Food", category: "Mental Clarity" },
  { title: "How Chronic Pain Affects Cognitive Function (And What Helps)", category: "Mental Clarity" },
  { title: "The Neuroplasticity Research That Changed How I Think About Aging", category: "Mental Clarity" },
  { title: "Why I Started a Book Club at 64 (It Wasn't About the Books)", category: "Mental Clarity" },
  { title: "The Connection Between Loneliness and Alzheimer's Risk", category: "Mental Clarity" },
  { title: "How I Use Mindfulness to Manage Anxiety Without Medication", category: "Mental Clarity" },
  { title: "The Case for Analog Hobbies in a Digital Age", category: "Mental Clarity" },
  { title: "Why Your Brain Needs Downtime More Than You Think", category: "Mental Clarity" },
  { title: "How I Improved My Working Memory at 67", category: "Mental Clarity" },
  { title: "The Cognitive Cost of Clutter (And How I Cleared Mine)", category: "Mental Clarity" },
  { title: "Why Older Adults Are Often the Most Creative People in the Room", category: "Mental Clarity" },

  // ── Emotional Health (50) ───────────────────────────────────────────────
  { title: "The Grief Nobody Talks About: Losing Your Former Self", category: "Emotional Health" },
  { title: "How I Finally Made Peace With My Father at 63", category: "Emotional Health" },
  { title: "Why Anger in Older Adults Is Often Unprocessed Grief", category: "Emotional Health" },
  { title: "The Difference Between Loneliness and Solitude (And Why It Matters)", category: "Emotional Health" },
  { title: "How I Learned to Sit With Discomfort Instead of Running From It", category: "Emotional Health" },
  { title: "Why I Started Therapy at 65 (And What I Wish I'd Done It Sooner)", category: "Emotional Health" },
  { title: "The Emotional Weight of Watching Parents Decline", category: "Emotional Health" },
  { title: "How to Forgive Someone Who Never Apologized", category: "Emotional Health" },
  { title: "Why Older Adults Are Often Happier Than Young People (The Research)", category: "Emotional Health" },
  { title: "The Midlife Reckoning That Changed Everything for Me", category: "Emotional Health" },
  { title: "How I Stopped People-Pleasing at 61 (And What It Cost Me)", category: "Emotional Health" },
  { title: "The Connection Between Unresolved Trauma and Physical Pain", category: "Emotional Health" },
  { title: "Why I Cried at My Retirement Party (And Wasn't Expecting To)", category: "Emotional Health" },
  { title: "How to Deal With the Emotional Aftermath of a Health Scare", category: "Emotional Health" },
  { title: "The Loneliness Epidemic Among Older Men (And What We Can Do)", category: "Emotional Health" },
  { title: "Why I Started Keeping a Feelings Journal at 64", category: "Emotional Health" },
  { title: "The Emotional Work of Becoming an Elder", category: "Emotional Health" },
  { title: "How I Rebuilt My Identity After My Career Ended", category: "Emotional Health" },
  { title: "The Difference Between Depression and Grief After Loss", category: "Emotional Health" },
  { title: "Why I Stopped Apologizing for Taking Up Space", category: "Emotional Health" },
  { title: "How to Have the Conversation About Death With Someone You Love", category: "Emotional Health" },
  { title: "The Emotional Cost of Carrying Old Stories About Yourself", category: "Emotional Health" },
  { title: "Why I Started Saying No More Often (And How It Changed My Relationships)", category: "Emotional Health" },
  { title: "The Role of Humor in Aging Well (It's More Than Coping)", category: "Emotional Health" },
  { title: "How I Processed the End of My Marriage at 59", category: "Emotional Health" },
  { title: "Why Vulnerability Gets Easier as You Get Older", category: "Emotional Health" },
  { title: "The Emotional Intelligence Skills That Matter Most After 60", category: "Emotional Health" },
  { title: "How I Stopped Comparing My Life to What I Thought It Would Be", category: "Emotional Health" },
  { title: "The Grief of Watching Friends Move Away or Die", category: "Emotional Health" },
  { title: "Why I Started Seeing a Grief Counselor After My Dog Died", category: "Emotional Health" },
  { title: "How to Rebuild Trust After It's Been Broken", category: "Emotional Health" },
  { title: "The Emotional Stages of Accepting a Chronic Diagnosis", category: "Emotional Health" },
  { title: "Why Older Adults Often Have a Better Relationship With Failure", category: "Emotional Health" },
  { title: "How I Learned to Ask for Help (The Hardest Thing I've Ever Done)", category: "Emotional Health" },
  { title: "The Connection Between Emotional Health and Physical Recovery", category: "Emotional Health" },
  { title: "Why I Started Crying More After 60 (And Why That's a Good Thing)", category: "Emotional Health" },
  { title: "How to Support a Partner Through Depression Without Losing Yourself", category: "Emotional Health" },
  { title: "The Emotional Freedom That Comes With Not Caring What People Think", category: "Emotional Health" },
  { title: "Why I Wrote Letters to Everyone I'd Wronged at 65", category: "Emotional Health" },
  { title: "How Gratitude Practice Changed My Relationship With Regret", category: "Emotional Health" },
  { title: "The Difference Between Acceptance and Giving Up", category: "Emotional Health" },
  { title: "Why I Started Talking About Death More Openly", category: "Emotional Health" },
  { title: "How to Grieve a Relationship That Ended Without Closure", category: "Emotional Health" },
  { title: "The Emotional Benefits of Having a Daily Ritual", category: "Emotional Health" },
  { title: "Why I Stopped Trying to Fix My Adult Children's Problems", category: "Emotional Health" },
  { title: "How I Made Peace With the Body I Have Now", category: "Emotional Health" },
  { title: "The Difference Between Contentment and Settling", category: "Emotional Health" },
  { title: "Why Older Adults Are Often the Best at Emotional Repair", category: "Emotional Health" },
  { title: "How I Use Art to Process Emotions I Can't Put Into Words", category: "Emotional Health" },
  { title: "The Emotional Work of Preparing for Your Own Death", category: "Emotional Health" },

  // ── Spiritual Practice (50) ─────────────────────────────────────────────
  { title: "What 40 Years of Meditation Taught Me About Dying", category: "Spiritual Practice" },
  { title: "Why I Left the Religion I Grew Up In (And What I Found Instead)", category: "Spiritual Practice" },
  { title: "The Difference Between Religion and Spirituality After 60", category: "Spiritual Practice" },
  { title: "How I Use Nature as My Primary Spiritual Practice", category: "Spiritual Practice" },
  { title: "Why Silence Is the Most Underrated Spiritual Tool", category: "Spiritual Practice" },
  { title: "The Contemplative Practices That Actually Work for Skeptics", category: "Spiritual Practice" },
  { title: "How I Rebuilt My Spiritual Life After a Faith Crisis at 58", category: "Spiritual Practice" },
  { title: "Why I Started a Daily Sitting Practice at 63 (Not Meditation, Something Else)", category: "Spiritual Practice" },
  { title: "The Spiritual Dimension of Chronic Illness", category: "Spiritual Practice" },
  { title: "How I Use Ritual to Mark the Seasons of My Life", category: "Spiritual Practice" },
  { title: "Why Older Adults Are Often the Most Spiritually Alive People I Know", category: "Spiritual Practice" },
  { title: "The Connection Between Gratitude and Spiritual Depth", category: "Spiritual Practice" },
  { title: "How I Learned to Pray Again After Decades Away", category: "Spiritual Practice" },
  { title: "Why I Started a Contemplative Reading Practice at 65", category: "Spiritual Practice" },
  { title: "The Spiritual Work of Letting Go", category: "Spiritual Practice" },
  { title: "How I Use Walking as a Moving Meditation", category: "Spiritual Practice" },
  { title: "Why Death Awareness Is the Most Spiritual Practice I Know", category: "Spiritual Practice" },
  { title: "The Role of Awe in Spiritual Wellbeing After 60", category: "Spiritual Practice" },
  { title: "How I Found Meaning in the Mundane", category: "Spiritual Practice" },
  { title: "Why I Started Keeping a Spiritual Journal at 62", category: "Spiritual Practice" },
  { title: "The Difference Between Spiritual Bypassing and Genuine Practice", category: "Spiritual Practice" },
  { title: "How I Use Music as a Gateway to the Sacred", category: "Spiritual Practice" },
  { title: "Why I Went on a Silent Retreat at 64 (And What Happened)", category: "Spiritual Practice" },
  { title: "The Spiritual Dimension of Service and Giving Back", category: "Spiritual Practice" },
  { title: "How I Reconcile Science and Spirituality After 60", category: "Spiritual Practice" },
  { title: "Why I Started Studying Buddhist Psychology at 67", category: "Spiritual Practice" },
  { title: "The Spiritual Practice of Forgiveness (It's Not What You Think)", category: "Spiritual Practice" },
  { title: "How I Use Breathwork to Access States I Can't Reach in Meditation", category: "Spiritual Practice" },
  { title: "Why I Started Attending a Different Kind of Church at 63", category: "Spiritual Practice" },
  { title: "The Connection Between Creativity and Spiritual Aliveness", category: "Spiritual Practice" },
  { title: "How I Use Darkness Retreats to Reset My Nervous System", category: "Spiritual Practice" },
  { title: "Why I Started Studying the Enneagram at 65 (And What It Revealed)", category: "Spiritual Practice" },
  { title: "The Spiritual Dimension of Physical Pain", category: "Spiritual Practice" },
  { title: "How I Use Sacred Texts From Multiple Traditions", category: "Spiritual Practice" },
  { title: "Why I Started a Gratitude Altar at 61", category: "Spiritual Practice" },
  { title: "The Role of Community in Spiritual Development After 60", category: "Spiritual Practice" },
  { title: "How I Learned to Trust the Timing of My Life", category: "Spiritual Practice" },
  { title: "Why Spiritual Maturity Looks Nothing Like I Expected", category: "Spiritual Practice" },
  { title: "The Connection Between Elderhood and Spiritual Authority", category: "Spiritual Practice" },
  { title: "How I Use Fasting as a Spiritual Practice (Not a Diet)", category: "Spiritual Practice" },
  { title: "Why I Started Studying Stoicism at 64", category: "Spiritual Practice" },
  { title: "The Spiritual Practice of Honest Self-Examination", category: "Spiritual Practice" },
  { title: "How I Use Ceremony to Mark Important Life Transitions", category: "Spiritual Practice" },
  { title: "Why I Started a Daily Practice of Blessing What I See", category: "Spiritual Practice" },
  { title: "The Difference Between Spiritual Experience and Spiritual Development", category: "Spiritual Practice" },
  { title: "How I Use Poetry as a Spiritual Practice", category: "Spiritual Practice" },
  { title: "Why I Started Studying Indigenous Wisdom Traditions at 66", category: "Spiritual Practice" },
  { title: "The Spiritual Work of Accepting Your Own Mortality", category: "Spiritual Practice" },
  { title: "How I Use the Body as a Spiritual Instrument", category: "Spiritual Practice" },
  { title: "Why I Believe the Second Half of Life Is the Spiritual Half", category: "Spiritual Practice" },

  // ── Social Connection (50) ──────────────────────────────────────────────
  { title: "Why I Ended Three Friendships at 62 (And Don't Regret It)", category: "Social Connection" },
  { title: "How I Made New Friends After 60 (It's Harder Than You Think)", category: "Social Connection" },
  { title: "The Difference Between Being Alone and Being Lonely", category: "Social Connection" },
  { title: "Why I Started a Men's Group at 65 (And What It Changed)", category: "Social Connection" },
  { title: "How to Maintain Long-Distance Friendships After Retirement", category: "Social Connection" },
  { title: "The Intergenerational Friendships That Changed My Life", category: "Social Connection" },
  { title: "Why I Started Volunteering at 63 (It Wasn't What I Expected)", category: "Social Connection" },
  { title: "How I Rebuilt My Social Life After My Marriage Ended", category: "Social Connection" },
  { title: "The Art of Being a Good Friend After 60", category: "Social Connection" },
  { title: "Why I Started Hosting Dinner Parties Again at 64", category: "Social Connection" },
  { title: "How to Have Difficult Conversations With Adult Children", category: "Social Connection" },
  { title: "The Social Costs of Retirement Nobody Warns You About", category: "Social Connection" },
  { title: "Why I Started a Neighborhood Walking Group at 62", category: "Social Connection" },
  { title: "How I Reconnected With Old Friends After 20 Years", category: "Social Connection" },
  { title: "The Role of Community in Longevity (The Research Is Clear)", category: "Social Connection" },
  { title: "Why I Started Mentoring Young People at 66", category: "Social Connection" },
  { title: "How to Navigate Family Gatherings When Relationships Are Strained", category: "Social Connection" },
  { title: "The Friendship Audit I Did at 63 (And What I Found)", category: "Social Connection" },
  { title: "Why I Started Saying Yes to More Invitations After 60", category: "Social Connection" },
  { title: "How I Use Technology to Stay Connected Without Losing Myself", category: "Social Connection" },
  { title: "The Difference Between Acquaintances and Real Friends After 60", category: "Social Connection" },
  { title: "Why I Started a Book Club (And What It's Really About)", category: "Social Connection" },
  { title: "How to Be a Good Grandparent Without Losing Your Own Life", category: "Social Connection" },
  { title: "The Social Benefits of Having a Regular Third Place", category: "Social Connection" },
  { title: "Why I Started Attending Community Events I Used to Skip", category: "Social Connection" },
  { title: "How I Navigated the Social Fallout of a Major Life Change", category: "Social Connection" },
  { title: "The Art of Asking for Help From People You Love", category: "Social Connection" },
  { title: "Why I Started a Weekly Phone Call Ritual With Old Friends", category: "Social Connection" },
  { title: "How to Maintain Your Identity in a Long-Term Partnership", category: "Social Connection" },
  { title: "The Social Isolation That Comes With Caregiving (And What Helps)", category: "Social Connection" },
  { title: "Why I Started Joining Clubs I Knew Nothing About at 65", category: "Social Connection" },
  { title: "How I Rebuilt Trust With My Adult Son After Years of Distance", category: "Social Connection" },
  { title: "The Difference Between Social Media and Real Connection", category: "Social Connection" },
  { title: "Why I Started Cooking for Neighbors I Barely Knew", category: "Social Connection" },
  { title: "How to Be Present With Someone Who Is Dying", category: "Social Connection" },
  { title: "The Social Benefits of Shared Physical Activity After 60", category: "Social Connection" },
  { title: "Why I Started Attending a Weekly Meditation Group at 63", category: "Social Connection" },
  { title: "How I Navigated Friendship Changes After a Major Health Event", category: "Social Connection" },
  { title: "The Art of Listening as a Gift You Can Give at Any Age", category: "Social Connection" },
  { title: "Why I Started Writing Letters Instead of Texts at 64", category: "Social Connection" },
  { title: "How to Find Your People After Moving to a New City After 60", category: "Social Connection" },
  { title: "The Connection Between Social Health and Physical Longevity", category: "Social Connection" },
  { title: "Why I Started a Neighborhood Tool-Sharing Program at 67", category: "Social Connection" },
  { title: "How I Use Shared Meals to Build Deeper Connections", category: "Social Connection" },
  { title: "The Role of Humor in Maintaining Long Friendships", category: "Social Connection" },
  { title: "Why I Started Attending a Weekly Farmers Market (It's Not About the Food)", category: "Social Connection" },
  { title: "How to Navigate the Social Complexity of Blended Families After 60", category: "Social Connection" },
  { title: "The Friendship Lessons I Learned From My Oldest Friend's Death", category: "Social Connection" },
  { title: "Why I Started Hosting Monthly Potlucks for People Over 60", category: "Social Connection" },
  { title: "How I Use Shared Projects to Build Friendships That Last", category: "Social Connection" },

  // ── Legacy and Purpose (50) ─────────────────────────────────────────────
  { title: "What I Want to Leave Behind (And It's Not Money)", category: "Legacy and Purpose" },
  { title: "How I Found My Purpose After Retirement (It Took Three Years)", category: "Legacy and Purpose" },
  { title: "Why I Started Writing My Memoir at 64 (Not to Publish It)", category: "Legacy and Purpose" },
  { title: "The Difference Between a Life Resume and a Legacy", category: "Legacy and Purpose" },
  { title: "How I Use Storytelling to Pass Down What Matters Most", category: "Legacy and Purpose" },
  { title: "Why I Started Recording Oral Histories With My Aging Parents", category: "Legacy and Purpose" },
  { title: "The Question That Changed How I Think About My Remaining Years", category: "Legacy and Purpose" },
  { title: "How I Decided What to Do With the Rest of My Life at 63", category: "Legacy and Purpose" },
  { title: "Why I Started a Foundation at 66 (And What I Learned)", category: "Legacy and Purpose" },
  { title: "The Difference Between Success and Significance After 60", category: "Legacy and Purpose" },
  { title: "How I Use Ethical Wills to Pass Down Values, Not Just Assets", category: "Legacy and Purpose" },
  { title: "Why I Started Mentoring at 65 (And What I Got Back)", category: "Legacy and Purpose" },
  { title: "The Legacy Conversation I Had With My Children at 62", category: "Legacy and Purpose" },
  { title: "How I Reconciled My Regrets With My Remaining Purpose", category: "Legacy and Purpose" },
  { title: "Why I Started a Community Garden at 67 (It Was Never About Vegetables)", category: "Legacy and Purpose" },
  { title: "The Role of Craft and Making in Living a Purposeful Life", category: "Legacy and Purpose" },
  { title: "How I Use My Professional Skills in Service After Retirement", category: "Legacy and Purpose" },
  { title: "Why I Started Teaching Free Classes at the Library at 64", category: "Legacy and Purpose" },
  { title: "The Difference Between Leaving a Legacy and Living One", category: "Legacy and Purpose" },
  { title: "How I Wrote Letters to My Grandchildren They'll Read When I'm Gone", category: "Legacy and Purpose" },
  { title: "Why I Started Documenting Family Recipes and Stories at 63", category: "Legacy and Purpose" },
  { title: "The Purpose That Found Me When I Stopped Looking", category: "Legacy and Purpose" },
  { title: "How I Use My Elder Status as a Form of Social Contribution", category: "Legacy and Purpose" },
  { title: "Why I Started a Scholarship Fund With Money I Was Going to Spend on Myself", category: "Legacy and Purpose" },
  { title: "The Difference Between Leaving Things and Leaving Meaning", category: "Legacy and Purpose" },
  { title: "How I Rebuilt My Sense of Purpose After a Major Health Crisis", category: "Legacy and Purpose" },
  { title: "Why I Started Volunteering in Hospice at 65", category: "Legacy and Purpose" },
  { title: "The Legacy Work That Came From My Darkest Year", category: "Legacy and Purpose" },
  { title: "How I Use Photography to Document What I Love Before It's Gone", category: "Legacy and Purpose" },
  { title: "Why I Started a Neighborhood History Project at 66", category: "Legacy and Purpose" },
  { title: "The Conversation About Death That Freed Me to Live More Fully", category: "Legacy and Purpose" },
  { title: "How I Found Meaning in Small Acts After Losing My Big Career", category: "Legacy and Purpose" },
  { title: "Why I Started Planting Trees I'll Never See Fully Grown", category: "Legacy and Purpose" },
  { title: "The Role of Beauty in Living a Meaningful Life After 60", category: "Legacy and Purpose" },
  { title: "How I Use My Life Story as a Teaching Tool for Younger People", category: "Legacy and Purpose" },
  { title: "Why I Started Giving Away Possessions That Matter to Me While I'm Still Alive", category: "Legacy and Purpose" },
  { title: "The Difference Between a Bucket List and a Purpose List", category: "Legacy and Purpose" },
  { title: "How I Turned My Biggest Failure Into My Most Important Contribution", category: "Legacy and Purpose" },
  { title: "Why I Started Writing Weekly Letters to My Grandchildren at 63", category: "Legacy and Purpose" },
  { title: "The Legacy of How You Treated People (It Outlasts Everything Else)", category: "Legacy and Purpose" },
  { title: "How I Use My Remaining Years as a Form of Artistic Expression", category: "Legacy and Purpose" },
  { title: "Why I Started a Neighborhood Repair Cafe at 65", category: "Legacy and Purpose" },
  { title: "The Difference Between Being Remembered and Mattering", category: "Legacy and Purpose" },
  { title: "How I Reconciled What I Built With What I Wish I'd Built", category: "Legacy and Purpose" },
  { title: "Why I Started Documenting My Town's Oral History at 68", category: "Legacy and Purpose" },
  { title: "The Purpose That Comes From Being Fully Present With What Is", category: "Legacy and Purpose" },
  { title: "How I Use My Elder Voice in Community Advocacy After 65", category: "Legacy and Purpose" },
  { title: "Why I Started a Peer Support Group for Men Over 60 at 64", category: "Legacy and Purpose" },
  { title: "The Legacy Conversation That Changed My Relationship With My Daughter", category: "Legacy and Purpose" },
  { title: "How I Decided What Matters Most in the Time I Have Left", category: "Legacy and Purpose" },

  // ── Conscious Aging (50) ────────────────────────────────────────────────
  { title: "What Conscious Aging Actually Means (It's Not What You Think)", category: "Conscious Aging" },
  { title: "The Difference Between Aging and Becoming", category: "Conscious Aging" },
  { title: "Why I Stopped Fighting My Age and Started Working With It", category: "Conscious Aging" },
  { title: "How I Use the Concept of Elderhood as a North Star", category: "Conscious Aging" },
  { title: "The Cultural Lies About Aging I Had to Unlearn", category: "Conscious Aging" },
  { title: "Why the Second Half of Life Is Not a Decline", category: "Conscious Aging" },
  { title: "How I Reframed Retirement as a Beginning, Not an End", category: "Conscious Aging" },
  { title: "The Gifts That Only Come With Age (And How to Receive Them)", category: "Conscious Aging" },
  { title: "Why I Stopped Trying to Look Younger and Started Trying to Feel Alive", category: "Conscious Aging" },
  { title: "The Difference Between Aging Gracefully and Aging Consciously", category: "Conscious Aging" },
  { title: "How I Use the Japanese Concept of Ikigai After 60", category: "Conscious Aging" },
  { title: "Why I Started Studying the Elder Archetype at 64", category: "Conscious Aging" },
  { title: "The Role of Acceptance in Conscious Aging (Without Resignation)", category: "Conscious Aging" },
  { title: "How I Learned to Honor the Body I Have Instead of Mourning the One I Had", category: "Conscious Aging" },
  { title: "Why Conscious Aging Requires Doing the Inner Work", category: "Conscious Aging" },
  { title: "The Wisdom That Only Comes From Having Lived Long Enough to Fail", category: "Conscious Aging" },
  { title: "How I Use the Concept of Completion to Approach the End of Life", category: "Conscious Aging" },
  { title: "Why I Started Studying Gerotranscendence at 65", category: "Conscious Aging" },
  { title: "The Difference Between Resignation and Acceptance After 60", category: "Conscious Aging" },
  { title: "How I Use the Stages of Conscious Aging as a Map", category: "Conscious Aging" },
  { title: "Why Older Adults Are Often the Most Alive People I Know", category: "Conscious Aging" },
  { title: "The Role of Humor in Aging Consciously", category: "Conscious Aging" },
  { title: "How I Reconcile the Loss of Physical Capacity With a Sense of Expansion", category: "Conscious Aging" },
  { title: "Why I Started Talking About Death at Dinner Parties at 63", category: "Conscious Aging" },
  { title: "The Conscious Aging Practice That Changed Everything for Me", category: "Conscious Aging" },
  { title: "How I Use Ritual to Mark the Passage of Time After 60", category: "Conscious Aging" },
  { title: "Why the Elder Role Is the Most Important Role I've Ever Played", category: "Conscious Aging" },
  { title: "The Difference Between Wisdom and Knowledge After 60", category: "Conscious Aging" },
  { title: "How I Learned to Receive Care Without Losing My Dignity", category: "Conscious Aging" },
  { title: "Why I Started Attending a Conscious Aging Group at 66", category: "Conscious Aging" },
  { title: "The Role of Beauty and Aesthetics in Aging Well", category: "Conscious Aging" },
  { title: "How I Use the Concept of Enough to Navigate Consumerism After 60", category: "Conscious Aging" },
  { title: "Why I Started Studying the Blue Zones Research at 64", category: "Conscious Aging" },
  { title: "The Difference Between Living Longer and Living Better", category: "Conscious Aging" },
  { title: "How I Use My Age as an Asset in Every Room I Enter", category: "Conscious Aging" },
  { title: "Why I Stopped Apologizing for Slowing Down", category: "Conscious Aging" },
  { title: "The Conscious Aging Practices of Indigenous Elders I've Studied", category: "Conscious Aging" },
  { title: "How I Reframe Every Physical Limitation as a Teacher", category: "Conscious Aging" },
  { title: "Why I Started a Death Cafe in My Community at 65", category: "Conscious Aging" },
  { title: "The Difference Between Aging in Place and Aging With Intention", category: "Conscious Aging" },
  { title: "How I Use the Concept of Completion in My Daily Practice", category: "Conscious Aging" },
  { title: "Why I Started Studying Carl Jung's Work on the Second Half of Life at 62", category: "Conscious Aging" },
  { title: "The Role of Creativity in Conscious Aging", category: "Conscious Aging" },
  { title: "How I Learned to Trust the Process of Aging Instead of Fighting It", category: "Conscious Aging" },
  { title: "Why I Started a Conscious Aging Reading Group at 64", category: "Conscious Aging" },
  { title: "The Difference Between an Elder and an Old Person", category: "Conscious Aging" },
  { title: "How I Use the Concept of Elderhood to Give My Remaining Years Meaning", category: "Conscious Aging" },
  { title: "Why I Believe Aging Is the Most Spiritual Journey Available to Us", category: "Conscious Aging" },
  { title: "The Conscious Aging Practices That Actually Work (From Someone Who's Tried Them All)", category: "Conscious Aging" },
  { title: "How I Found Peace With the Life I've Lived", category: "Conscious Aging" },

  // ── Relationships (50) ──────────────────────────────────────────────────
  { title: "How I Rebuilt My Marriage After 30 Years of Drifting Apart", category: "Relationships" },
  { title: "Why I Started Dating Again at 64 (And What I Learned)", category: "Relationships" },
  { title: "The Difference Between a Companion and a Partner After 60", category: "Relationships" },
  { title: "How I Navigated My Husband's Retirement Without Losing My Mind", category: "Relationships" },
  { title: "Why I Chose to Stay Single After My Divorce at 58", category: "Relationships" },
  { title: "The Conversation About Money That Almost Ended My Marriage", category: "Relationships" },
  { title: "How I Rebuilt My Relationship With My Estranged Daughter at 63", category: "Relationships" },
  { title: "Why I Started Couples Therapy at 61 (Before We Needed It)", category: "Relationships" },
  { title: "The Difference Between Intimacy and Sex After 60 (Both Matter)", category: "Relationships" },
  { title: "How I Navigated Becoming a Caregiver for My Partner", category: "Relationships" },
  { title: "Why I Started Having Deeper Conversations With My Adult Children", category: "Relationships" },
  { title: "The Role of Physical Affection in Long-Term Partnerships After 60", category: "Relationships" },
  { title: "How I Learned to Fight Better With My Partner at 62", category: "Relationships" },
  { title: "Why I Started Being More Honest With People I Love", category: "Relationships" },
  { title: "The Relationship Patterns I Finally Broke at 60", category: "Relationships" },
  { title: "How I Navigated My Partner's Serious Illness Without Losing Myself", category: "Relationships" },
  { title: "Why I Started Having Weekly Check-Ins With My Partner at 63", category: "Relationships" },
  { title: "The Difference Between Dependency and Interdependency in Long Partnerships", category: "Relationships" },
  { title: "How I Rebuilt Trust With My Brother After a Decade of Silence", category: "Relationships" },
  { title: "Why I Started Being More Vulnerable With the People Closest to Me", category: "Relationships" },
  { title: "The Conversation About Death I Had With My Partner at 64", category: "Relationships" },
  { title: "How I Navigated Blended Family Complexity After Remarrying at 60", category: "Relationships" },
  { title: "Why I Started Saying 'I Love You' More Often at 62", category: "Relationships" },
  { title: "The Role of Shared Meaning in Long-Term Relationships After 60", category: "Relationships" },
  { title: "How I Learned to Receive Love Without Deflecting It", category: "Relationships" },
  { title: "Why I Started Prioritizing My Marriage Over My Career at 59", category: "Relationships" },
  { title: "The Difference Between a Good Relationship and a Great One After 60", category: "Relationships" },
  { title: "How I Navigated My Adult Children's Disapproval of My New Partner", category: "Relationships" },
  { title: "Why I Started Writing Love Letters to My Partner of 30 Years", category: "Relationships" },
  { title: "The Relationship Repair Conversation That Changed Everything", category: "Relationships" },
  { title: "How I Learned to Be Alone in a Partnership (It's a Skill)", category: "Relationships" },
  { title: "Why I Started Being More Direct About What I Need at 63", category: "Relationships" },
  { title: "The Difference Between Forgiveness and Reconciliation", category: "Relationships" },
  { title: "How I Navigated the Death of My Partner and Found My Way Back", category: "Relationships" },
  { title: "Why I Started Having Monthly 'State of the Relationship' Conversations at 61", category: "Relationships" },
  { title: "The Role of Humor in Keeping a Long Partnership Alive", category: "Relationships" },
  { title: "How I Learned to Stop Keeping Score in My Marriage", category: "Relationships" },
  { title: "Why I Started Asking My Partner What They Need Instead of Assuming", category: "Relationships" },
  { title: "The Difference Between Loneliness in a Relationship and Solitude", category: "Relationships" },
  { title: "How I Rebuilt My Relationship With My Father Before He Died", category: "Relationships" },
  { title: "Why I Started Being More Generous With My Time and Attention at 64", category: "Relationships" },
  { title: "The Attachment Patterns I Discovered in Therapy at 62 (And How I Changed Them)", category: "Relationships" },
  { title: "How I Navigate Differences in Energy Level With My Partner After 60", category: "Relationships" },
  { title: "Why I Started Asking for What I Want in My Relationships", category: "Relationships" },
  { title: "The Difference Between a Healthy Relationship and a Comfortable One", category: "Relationships" },
  { title: "How I Learned to Apologize Properly at 63 (It's Harder Than It Sounds)", category: "Relationships" },
  { title: "Why I Started Treating My Oldest Friendships Like Investments", category: "Relationships" },
  { title: "The Role of Shared Adventure in Keeping Relationships Alive After 60", category: "Relationships" },
  { title: "How I Navigated My Partner's Depression Without Losing Myself", category: "Relationships" },
  { title: "Why I Believe Long Relationships Are the Greatest Spiritual Practice", category: "Relationships" },

  // ── Practical Wisdom (50) ───────────────────────────────────────────────
  { title: "The Financial Conversation I Wish I'd Had at 50", category: "Practical Wisdom" },
  { title: "How I Simplified My Life at 63 (And What I Gave Up)", category: "Practical Wisdom" },
  { title: "Why I Started Doing Estate Planning at 60 (Before I Needed To)", category: "Practical Wisdom" },
  { title: "The Downsizing Decision That Changed My Life at 64", category: "Practical Wisdom" },
  { title: "How I Navigate the Healthcare System After 60 (What Nobody Tells You)", category: "Practical Wisdom" },
  { title: "Why I Started Keeping a Personal Board of Directors at 62", category: "Practical Wisdom" },
  { title: "The Advance Directive Conversation I Had With My Family at 63", category: "Practical Wisdom" },
  { title: "How I Manage My Energy Instead of My Time After 60", category: "Practical Wisdom" },
  { title: "Why I Started Saying No to More Things at 61 (And How I Did It)", category: "Practical Wisdom" },
  { title: "The Technology Tools That Actually Help Me Age Well", category: "Practical Wisdom" },
  { title: "How I Prepared for Retirement Emotionally, Not Just Financially", category: "Practical Wisdom" },
  { title: "Why I Started Keeping a Daily Practice Log at 64", category: "Practical Wisdom" },
  { title: "The Home Modification That Made the Biggest Difference at 65", category: "Practical Wisdom" },
  { title: "How I Navigate Medical Appointments Without Feeling Dismissed", category: "Practical Wisdom" },
  { title: "Why I Started a Weekly Review Practice at 62", category: "Practical Wisdom" },
  { title: "The Financial Simplification That Reduced My Stress by Half", category: "Practical Wisdom" },
  { title: "How I Built a Support Network Before I Needed One", category: "Practical Wisdom" },
  { title: "Why I Started Keeping a Medication Log at 63 (And What I Found)", category: "Practical Wisdom" },
  { title: "The Conversation About Driving I Had With My Father at 70", category: "Practical Wisdom" },
  { title: "How I Use a Personal Mission Statement to Make Decisions After 60", category: "Practical Wisdom" },
  { title: "Why I Started Doing Annual Life Reviews at 62", category: "Practical Wisdom" },
  { title: "The Decluttering Process That Took Three Years and Changed My Life", category: "Practical Wisdom" },
  { title: "How I Navigate the Complexity of Medicare After 65", category: "Practical Wisdom" },
  { title: "Why I Started Keeping a Gratitude and Accomplishment Journal at 63", category: "Practical Wisdom" },
  { title: "The Retirement Income Strategy That Let Me Stop Worrying", category: "Practical Wisdom" },
  { title: "How I Use Batching to Manage the Administrative Burden of Aging", category: "Practical Wisdom" },
  { title: "Why I Started Having Annual Conversations With My Financial Advisor at 60", category: "Practical Wisdom" },
  { title: "The Home Safety Assessment I Did at 65 (And What I Changed)", category: "Practical Wisdom" },
  { title: "How I Prepared My Digital Life for Death (So My Family Doesn't Have To)", category: "Practical Wisdom" },
  { title: "Why I Started Keeping a Health Journal at 62", category: "Practical Wisdom" },
  { title: "The Conversation About Long-Term Care I Had With My Spouse at 61", category: "Practical Wisdom" },
  { title: "How I Manage Chronic Conditions Without Letting Them Manage Me", category: "Practical Wisdom" },
  { title: "Why I Started Batch Cooking on Sundays at 63 (It Changed My Health)", category: "Practical Wisdom" },
  { title: "The Social Security Timing Decision I Made at 62 (And Why)", category: "Practical Wisdom" },
  { title: "How I Use a Simple System to Keep My Life Organized After 60", category: "Practical Wisdom" },
  { title: "Why I Started Keeping an Emergency Information Binder at 64", category: "Practical Wisdom" },
  { title: "The Conversation About Housing I Had With My Adult Children at 65", category: "Practical Wisdom" },
  { title: "How I Navigate the Complexity of Prescription Drug Coverage After 65", category: "Practical Wisdom" },
  { title: "Why I Started Doing Regular Financial Check-Ins at 62", category: "Practical Wisdom" },
  { title: "The Habit Stacking System I Use to Maintain My Health Practices", category: "Practical Wisdom" },
  { title: "How I Built a Morning Routine That Actually Sticks at 64", category: "Practical Wisdom" },
  { title: "Why I Started Keeping a Simple Budget After 60 (I Wasn't Doing It Before)", category: "Practical Wisdom" },
  { title: "The Conversation About Inheritance I Had With My Children at 63", category: "Practical Wisdom" },
  { title: "How I Use a Weekly Planning Session to Stay on Top of My Health", category: "Practical Wisdom" },
  { title: "Why I Started Keeping a List of What Brings Me Joy at 62", category: "Practical Wisdom" },
  { title: "The Technology Boundaries I Set at 63 (And How They Changed My Life)", category: "Practical Wisdom" },
  { title: "How I Navigate the Emotional Complexity of Giving Up My Car at 70", category: "Practical Wisdom" },
  { title: "Why I Started Keeping a 'What I've Learned' Journal at 64", category: "Practical Wisdom" },
  { title: "The Retirement Transition Plan I Wish I'd Made Five Years Earlier", category: "Practical Wisdom" },
  { title: "How I Use Simple Systems to Maintain My Physical and Mental Health After 60", category: "Practical Wisdom" },

  // ── Creativity and Expression (50) ──────────────────────────────────────
  { title: "Why I Started Painting at 63 (I Had No Talent and That Was the Point)", category: "Creativity and Expression" },
  { title: "How I Use Writing to Process What I Can't Say Out Loud", category: "Creativity and Expression" },
  { title: "The Creative Practice That Saved My Life After Retirement", category: "Creativity and Expression" },
  { title: "Why I Started Making Pottery at 65 (And What It Did to My Brain)", category: "Creativity and Expression" },
  { title: "How I Rebuilt My Creative Life After 30 Years of Not Making Anything", category: "Creativity and Expression" },
  { title: "The Difference Between Art as Product and Art as Practice", category: "Creativity and Expression" },
  { title: "Why I Started Playing Music Again at 62 (After 25 Years Away)", category: "Creativity and Expression" },
  { title: "How I Use Photography to Stay Present and Curious After 60", category: "Creativity and Expression" },
  { title: "The Creative Block I Had at 63 and How I Got Through It", category: "Creativity and Expression" },
  { title: "Why I Started Writing Poetry at 66 (I Was Terrible at First)", category: "Creativity and Expression" },
  { title: "How I Use Woodworking as a Meditation Practice", category: "Creativity and Expression" },
  { title: "The Role of Making Things in Living a Meaningful Life After 60", category: "Creativity and Expression" },
  { title: "Why I Started Keeping a Sketchbook at 64 (No Drawing Experience Required)", category: "Creativity and Expression" },
  { title: "How I Use Cooking as a Creative Practice, Not Just a Chore", category: "Creativity and Expression" },
  { title: "The Creative Practice That Connects Me to My Grandchildren", category: "Creativity and Expression" },
  { title: "Why I Started a Creative Morning Practice at 63", category: "Creativity and Expression" },
  { title: "How I Use Gardening as a Form of Creative Expression", category: "Creativity and Expression" },
  { title: "The Difference Between Creativity and Productivity (I Confused Them for Years)", category: "Creativity and Expression" },
  { title: "Why I Started Knitting at 65 (It's Not What You Think)", category: "Creativity and Expression" },
  { title: "How I Use Storytelling to Connect With My Family Across Generations", category: "Creativity and Expression" },
  { title: "The Creative Practice That Helped Me Process Grief", category: "Creativity and Expression" },
  { title: "Why I Started Making Collages at 62 (No Art Background Required)", category: "Creativity and Expression" },
  { title: "How I Use Dance as a Form of Moving Meditation After 60", category: "Creativity and Expression" },
  { title: "The Role of Play in Creative Practice After 60", category: "Creativity and Expression" },
  { title: "Why I Started a Creative Community at 64 (And What I Found)", category: "Creativity and Expression" },
  { title: "How I Use Calligraphy as a Contemplative Practice", category: "Creativity and Expression" },
  { title: "The Creative Practice That Helped Me Find My Voice After Retirement", category: "Creativity and Expression" },
  { title: "Why I Started Bookbinding at 66 (The Most Meditative Thing I've Ever Done)", category: "Creativity and Expression" },
  { title: "How I Use Fiber Arts to Process Emotion and Build Community", category: "Creativity and Expression" },
  { title: "The Difference Between Creating for Others and Creating for Yourself", category: "Creativity and Expression" },
  { title: "Why I Started a Daily Drawing Practice at 63 (Five Minutes a Day)", category: "Creativity and Expression" },
  { title: "How I Use Mosaic-Making as a Metaphor for My Life After 60", category: "Creativity and Expression" },
  { title: "The Creative Practice That Helped Me Reconnect With My Body", category: "Creativity and Expression" },
  { title: "Why I Started Writing Short Stories at 65 (And What I Discovered)", category: "Creativity and Expression" },
  { title: "How I Use Textile Arts to Connect With My Cultural Heritage", category: "Creativity and Expression" },
  { title: "The Role of Imperfection in Creative Practice After 60", category: "Creativity and Expression" },
  { title: "Why I Started a Creative Journal at 62 (Different From a Diary)", category: "Creativity and Expression" },
  { title: "How I Use Sculpture to Explore What I Can't Say in Words", category: "Creativity and Expression" },
  { title: "The Creative Practice That Helped Me Navigate a Major Life Transition", category: "Creativity and Expression" },
  { title: "Why I Started Making Music With My Grandchildren at 64", category: "Creativity and Expression" },
  { title: "How I Use Printmaking as a Contemplative Practice", category: "Creativity and Expression" },
  { title: "The Difference Between a Hobby and a Creative Practice", category: "Creativity and Expression" },
  { title: "Why I Started a Creative Writing Group at 65 (For People Who've Never Written)", category: "Creativity and Expression" },
  { title: "How I Use Watercolor to Stay Present and Observant After 60", category: "Creativity and Expression" },
  { title: "The Creative Practice That Helped Me Process My Father's Death", category: "Creativity and Expression" },
  { title: "Why I Started Making Handmade Books at 63 (And Giving Them Away)", category: "Creativity and Expression" },
  { title: "How I Use Ceramics to Explore the Relationship Between Control and Surrender", category: "Creativity and Expression" },
  { title: "The Role of Creativity in Cognitive Health After 60 (The Research Is Clear)", category: "Creativity and Expression" },
  { title: "Why I Started a Community Mural Project at 66", category: "Creativity and Expression" },
  { title: "How I Use Creative Practice to Stay Connected to What Matters Most", category: "Creativity and Expression" },

  // ── Nature and Place (50) ───────────────────────────────────────────────
  { title: "Why I Started Forest Bathing at 63 (And What Changed)", category: "Nature and Place" },
  { title: "How I Use My Garden as a Spiritual Practice", category: "Nature and Place" },
  { title: "The Nature Practice That Helped Me Manage Anxiety Without Medication", category: "Nature and Place" },
  { title: "Why I Started Birdwatching at 65 (The Most Meditative Thing I've Ever Done)", category: "Nature and Place" },
  { title: "How I Use the Seasons as a Framework for My Inner Life", category: "Nature and Place" },
  { title: "The Connection Between Time in Nature and Cognitive Health After 60", category: "Nature and Place" },
  { title: "Why I Started Wild Swimming at 62 (And What It Did to My Nervous System)", category: "Nature and Place" },
  { title: "How I Use Stargazing as a Contemplative Practice", category: "Nature and Place" },
  { title: "The Nature Journal I've Kept for Five Years (And What It's Taught Me)", category: "Nature and Place" },
  { title: "Why I Started Growing My Own Food at 64 (It Wasn't About the Food)", category: "Nature and Place" },
  { title: "How I Use Daily Walks in Nature as My Primary Mental Health Practice", category: "Nature and Place" },
  { title: "The Connection Between Place and Identity After 60", category: "Nature and Place" },
  { title: "Why I Started Camping Alone at 63 (The Most Terrifying and Liberating Thing)", category: "Nature and Place" },
  { title: "How I Use the Ocean as a Teacher", category: "Nature and Place" },
  { title: "The Role of Wild Places in My Emotional and Spiritual Health", category: "Nature and Place" },
  { title: "Why I Started a Native Plant Garden at 65 (And What I Learned)", category: "Nature and Place" },
  { title: "How I Use Seasonal Rituals to Stay Connected to the Natural World", category: "Nature and Place" },
  { title: "The Connection Between Soil and Wellbeing (The Research Is Fascinating)", category: "Nature and Place" },
  { title: "Why I Started Hiking Alone at 62 (And What I Found)", category: "Nature and Place" },
  { title: "How I Use My Relationship With Place as a Spiritual Anchor", category: "Nature and Place" },
  { title: "The Nature Practice That Helped Me Grieve", category: "Nature and Place" },
  { title: "Why I Started Keeping a Phenology Journal at 64", category: "Nature and Place" },
  { title: "How I Use the Concept of Rewilding to Think About My Own Aging", category: "Nature and Place" },
  { title: "The Connection Between Nature and Creativity After 60", category: "Nature and Place" },
  { title: "Why I Started a Sit Spot Practice at 63 (Sitting in the Same Place Every Day)", category: "Nature and Place" },
  { title: "How I Use Weather as a Teacher About Impermanence", category: "Nature and Place" },
  { title: "The Role of Animals in My Emotional and Spiritual Health After 60", category: "Nature and Place" },
  { title: "Why I Started Foraging at 65 (And What It Changed About How I See the World)", category: "Nature and Place" },
  { title: "How I Use the Night Sky to Cultivate Awe and Perspective", category: "Nature and Place" },
  { title: "The Connection Between Place Attachment and Wellbeing After 60", category: "Nature and Place" },
  { title: "Why I Started a Composting Practice at 62 (It's More Than Recycling)", category: "Nature and Place" },
  { title: "How I Use Long Solo Walks to Process What I Can't Think Through at Home", category: "Nature and Place" },
  { title: "The Nature Practice That Helped Me Reconnect With My Body After Illness", category: "Nature and Place" },
  { title: "Why I Started Keeping a Weather Journal at 64", category: "Nature and Place" },
  { title: "How I Use the Concept of Ecological Grief to Understand My Own Aging", category: "Nature and Place" },
  { title: "The Connection Between Gardening and Mental Health After 60 (The Research)", category: "Nature and Place" },
  { title: "Why I Started a Daily Sunrise Practice at 63", category: "Nature and Place" },
  { title: "How I Use My Relationship With Trees as a Contemplative Practice", category: "Nature and Place" },
  { title: "The Role of Water in My Spiritual and Emotional Life After 60", category: "Nature and Place" },
  { title: "Why I Started Studying Permaculture at 65 (And How It Changed My Thinking)", category: "Nature and Place" },
  { title: "How I Use the Concept of Deep Time to Put My Life in Perspective", category: "Nature and Place" },
  { title: "The Nature Practice That Helped Me Manage Chronic Pain", category: "Nature and Place" },
  { title: "Why I Started a Dawn Chorus Listening Practice at 62", category: "Nature and Place" },
  { title: "How I Use the Concept of Succession in Nature to Think About My Own Life", category: "Nature and Place" },
  { title: "The Connection Between Outdoor Light and Sleep Quality After 60", category: "Nature and Place" },
  { title: "Why I Started a Barefoot Walking Practice at 64 (Grounding Is Real)", category: "Nature and Place" },
  { title: "How I Use Wild Swimming as a Form of Shock Therapy for the Soul", category: "Nature and Place" },
  { title: "The Role of Silence in Nature as a Restorative Practice After 60", category: "Nature and Place" },
  { title: "Why I Started a Daily Nature Photography Practice at 63", category: "Nature and Place" },
  { title: "How I Use My Relationship With the Natural World as My Primary Spiritual Practice", category: "Nature and Place" },
];

function slugify(title) {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .substring(0, 200);
}

async function main() {
  const conn = await mysql.createConnection(process.env.DATABASE_URL);
  
  // Get existing slugs to avoid duplicates
  const [existingRows] = await conn.execute('SELECT slug FROM articles');
  const existingSlugs = new Set(existingRows.map(r => r.slug));
  
  const topics = TOPICS.slice(0, LIMIT);
  let inserted = 0;
  let skipped = 0;
  
  for (const topic of topics) {
    const slug = slugify(topic.title);
    
    if (existingSlugs.has(slug)) {
      skipped++;
      continue;
    }
    
    if (DRY_RUN) {
      console.log(`[DRY RUN] Would queue: "${topic.title}" (${topic.category})`);
      inserted++;
      continue;
    }
    
    try {
      await conn.execute(
        `INSERT INTO articles 
          (slug, title, category, body, author, status, queuedAt, wordCount, readingTime, createdAt, updatedAt)
         VALUES (?, ?, ?, ?, 'Kalesh', 'queued', NOW(), 0, 0, NOW(), NOW())`,
        [slug, topic.title, topic.category, '']
      );
      existingSlugs.add(slug);
      inserted++;
      
      if (inserted % 50 === 0) {
        console.log(`[BulkSeed] Queued ${inserted} articles so far...`);
      }
    } catch (err) {
      if (err.code === 'ER_DUP_ENTRY') {
        skipped++;
      } else {
        console.error(`[BulkSeed] Error inserting "${topic.title}":`, err.message);
      }
    }
  }
  
  await conn.end();
  
  console.log(`\n[BulkSeed] Complete:`);
  console.log(`  Queued: ${inserted}`);
  console.log(`  Skipped (duplicate): ${skipped}`);
  console.log(`  Total in list: ${topics.length}`);
  
  if (!DRY_RUN) {
    const [countRows] = await mysql.createConnection(process.env.DATABASE_URL)
      .then(async c => { const r = await c.execute("SELECT COUNT(*) as cnt FROM articles WHERE status='queued'"); await c.end(); return r; });
    console.log(`  Total queued in DB: ${countRows[0].cnt}`);
  }
}

main().catch(err => { console.error(err); process.exit(1); });
